"""What the built wheel and sdist contain: the licence, and nothing stray (1.0.1).

PyPI shows the licence from the distribution, and a bare ``uv build`` packs whatever sits in
``src/avianki``, tracked or not. This builds both from a scratch copy of the project (with junk
files planted in the package) and checks the result.
"""

from __future__ import annotations

import shutil
import subprocess
import tarfile
import zipfile
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
JUNK = ("junk.apkg", "notes.orig", "debug.log", ".env", "edit.swp", "patch.rej", "old.bak")

pytestmark = pytest.mark.skipif(shutil.which("uv") is None, reason="uv is needed to build")


@pytest.fixture(scope="module")
def built(tmp_path_factory: pytest.TempPathFactory) -> tuple[Path, Path, str]:
    """``(wheel, sdist, uv's stderr)`` built from a copy of the project with junk planted."""
    project = tmp_path_factory.mktemp("project")
    for name in ("pyproject.toml", "LICENSE", "README.md"):
        shutil.copy2(REPO_ROOT / name, project / name)
    shutil.copytree(
        REPO_ROOT / "src", project / "src", ignore=shutil.ignore_patterns("__pycache__", "*.pyc")
    )
    for name in JUNK:
        (project / "src" / "avianki" / name).write_text("not part of the package")
    out = project / "dist"
    done = subprocess.run(
        ["uv", "build", "--out-dir", str(out), str(project)],
        check=True,
        capture_output=True,
        text=True,
        timeout=600,
    )
    (wheel,) = out.glob("avianki-*.whl")
    (sdist,) = out.glob("avianki-*.tar.gz")
    return wheel, sdist, done.stderr


def test_the_wheel_carries_the_licence(built) -> None:
    wheel, _, _ = built
    with zipfile.ZipFile(wheel) as zf:
        licences = [n for n in zf.namelist() if n.endswith("/licenses/LICENSE")]
        assert len(licences) == 1, zf.namelist()
        assert zf.read(licences[0]).replace(b"\r\n", b"\n") == (REPO_ROOT / "LICENSE").read_bytes().replace(
            b"\r\n", b"\n"
        )
        metadata = zf.read(licences[0].split("/licenses/")[0] + "/METADATA").decode()
    assert "License-Expression: MIT" in metadata
    assert "License-File: LICENSE" in metadata
    assert "License ::" not in metadata  # the deprecated classifier is gone


def test_the_sdist_carries_the_licence(built) -> None:
    _, sdist, _ = built
    with tarfile.open(sdist) as tf:
        names = tf.getnames()
    root = names[0].split("/")[0]
    assert f"{root}/LICENSE" in names


def test_neither_distribution_contains_untracked_junk(built) -> None:
    wheel, sdist, _ = built
    with tarfile.open(sdist) as tf:
        sdist_names = tf.getnames()
    with zipfile.ZipFile(wheel) as zf:
        wheel_names = zf.namelist()
    for name in JUNK:
        assert not [n for n in sdist_names + wheel_names if n.endswith("/" + name)], name


def test_the_sdist_holds_only_the_project_files(built) -> None:
    _, sdist, _ = built
    with tarfile.open(sdist) as tf:
        names = tf.getnames()
    root = names[0].split("/")[0]
    top = {n.split("/")[1] for n in names if "/" in n}
    # pyproject.toml.orig is the original pyproject that uv_build keeps beside the rewritten one;
    # it is generated by the build, not picked up from the working directory.
    assert top == {"PKG-INFO", "pyproject.toml", "pyproject.toml.orig", "LICENSE", "README.md", "src"}
    assert not [n for n in names if "__pycache__" in n or n.endswith(".pyc")], root


def test_building_raises_no_licence_warnings(built) -> None:
    _, _, stderr = built
    assert "license" not in stderr.lower(), stderr
